### ISSUE TITLE
Windows/Linux/MacOS/Web support

### ISSUE THREAD

**Issue by AlivE-git** [vovagorodok/ble_ota_app#19]
I am trying to compile an application for Windows. When running with debugging, I get the following error:
![image](https://github.com/vovagorodok/ble_ota_app/assets/12865205/e054fac1-6a1f-42aa-aa9d-4808d1194e86)
If I run it without debugging, the application starts, but the device list is empty.

**Comment by vovagorodok** [comment]
Because internal `flutter_reactive_ble` library  https://github.com/vovagorodok/ble_ota_app?tab=readme-ov-file#bleota  supports only Android and iOS for this moment.   
I'll think about this in future, perhaps by adding additional support of BLE libraries `bluetooth_low_energy` and `flutter_web_bluetooth` libraries

**Comment by vovagorodok** [comment]
Initial implementation: https://github.com/vovagorodok/ble_ota_app/pull/20

**Comment by vovagorodok** [comment]
Merged with support of couple of library from: https://fluttergems.dev/bluetooth-nfc-beacon/
